import React from "react";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

const RootLayout: React.FC<{children: React.ReactNode}> = ({children}) => {
	return (
		<>
			<title>{metadata.title}</title>
			<meta name="description" content={metadata.description} />
			<main>{children}</main>
		</>
	);
};

export default RootLayout;
